### ISSUE TITLE
Ability to specify a link

### ISSUE THREAD

**Issue by acidjazz** [AlexBeauchemin/gobadge#2]
i'd like to link my test actions from the badge:

`
[![Coverage](https://img.shields.io/badge/Coverage-9.8%25-red)](https://github.com/my/repo/actions/workflows/test.yml)
`

Ideally if you can preserve/save the original link that would be awesome - but an optional parameter like `-link` will work as well

**Comment by acidjazz** [comment]
gave it a shot - apologies for my formatter https://github.com/AlexBeauchemin/gobadge/pull/3

**Comment by AlexBeauchemin** [comment]
This has been merged, I don't use go anymore so if there's any problem with that feature it can be reopened and fixed
Thanks
